export const dataChart = {
  data: [
    {
      month: "01",
      unit: "cilincing",
      type: "pln",
      value: 0,
    },
    {
      month: "02",
      unit: "cilincing",
      type: "pln",
      value: 0,
    },
    {
      month: "03",
      unit: "cilincing",
      type: "pln",
      value: 0,
    },
    {
      month: "04",
      unit: "cilincing",
      type: "pln",
      value: 0,
    },
    {
      month: "05",
      unit: "cilincing",
      type: "pln",
      value: 0,
    },
    {
      month: "06",
      unit: "cilincing",
      type: "pln",
      value: 0,
    },
    {
      month: "07",
      unit: "cilincing",
      type: "pln",
      value: 3222026.893,
    },
    {
      month: "08",
      unit: "cilincing",
      type: "pln",
      value: 3315442.271,
    },
    {
      month: "09",
      unit: "cilincing",
      type: "pln",
      value: 4977379.929,
    },
    {
      month: "10",
      unit: "cilincing",
      type: "pln",
      value: 4901006.772,
    },
    {
      month: "11",
      unit: "cilincing",
      type: "pln",
      value: 0,
    },
    {
      month: "12",
      unit: "cilincing",
      type: "pln",
      value: 0,
    },
    {
      month: "01",
      unit: "kbn",
      type: "pln",
      value: 0,
    },
    {
      month: "02",
      unit: "kbn",
      type: "pln",
      value: 0,
    },
    {
      month: "03",
      unit: "kbn",
      type: "pln",
      value: 0,
    },
    {
      month: "04",
      unit: "kbn",
      type: "pln",
      value: 0,
    },
    {
      month: "05",
      unit: "kbn",
      type: "pln",
      value: 0,
    },
    {
      month: "06",
      unit: "kbn",
      type: "pln",
      value: 0,
    },
    {
      month: "07",
      unit: "kbn",
      type: "pln",
      value: 0,
    },
    {
      month: "08",
      unit: "kbn",
      type: "pln",
      value: 0,
    },
    {
      month: "09",
      unit: "kbn",
      type: "pln",
      value: 0,
    },
    {
      month: "10",
      unit: "kbn",
      type: "pln",
      value: 0,
    },
    {
      month: "11",
      unit: "kbn",
      type: "pln",
      value: 0,
    },
    {
      month: "12",
      unit: "kbn",
      type: "pln",
      value: 0,
    },
    {
      month: "01",
      unit: "cibitung",
      type: "pln",
      value: 0,
    },
    {
      month: "02",
      unit: "cibitung",
      type: "pln",
      value: 0,
    },
    {
      month: "03",
      unit: "cibitung",
      type: "pln",
      value: 0,
    },
    {
      month: "04",
      unit: "cibitung",
      type: "pln",
      value: 0,
    },
    {
      month: "05",
      unit: "cibitung",
      type: "pln",
      value: 0,
    },
    {
      month: "06",
      unit: "cibitung",
      type: "pln",
      value: 0,
    },
    {
      month: "07",
      unit: "cibitung",
      type: "pln",
      value: 0,
    },
    {
      month: "08",
      unit: "cibitung",
      type: "pln",
      value: 0,
    },
    {
      month: "09",
      unit: "cibitung",
      type: "pln",
      value: 0,
    },
    {
      month: "10",
      unit: "cibitung",
      type: "pln",
      value: 0,
    },
    {
      month: "11",
      unit: "cibitung",
      type: "pln",
      value: 0,
    },
    {
      month: "12",
      unit: "cibitung",
      type: "pln",
      value: 0,
    },
    {
      month: "01",
      unit: "cilincing",
      type: "genzet",
      value: 0,
    },
    {
      month: "02",
      unit: "cilincing",
      type: "genzet",
      value: 0,
    },
    {
      month: "03",
      unit: "cilincing",
      type: "genzet",
      value: 0,
    },
    {
      month: "04",
      unit: "cilincing",
      type: "genzet",
      value: 0,
    },
    {
      month: "05",
      unit: "cilincing",
      type: "genzet",
      value: 0,
    },
    {
      month: "06",
      unit: "cilincing",
      type: "genzet",
      value: 0,
    },
    {
      month: "07",
      unit: "cilincing",
      type: "genzet",
      value: 0,
    },
    {
      month: "08",
      unit: "cilincing",
      type: "genzet",
      value: 0,
    },
    {
      month: "09",
      unit: "cilincing",
      type: "genzet",
      value: 0,
    },
    {
      month: "10",
      unit: "cilincing",
      type: "genzet",
      value: 0,
    },
    {
      month: "11",
      unit: "cilincing",
      type: "genzet",
      value: 0,
    },
    {
      month: "12",
      unit: "cilincing",
      type: "genzet",
      value: 0,
    },
    {
      month: "01",
      unit: "kbn",
      type: "genzet",
      value: 0,
    },
    {
      month: "02",
      unit: "kbn",
      type: "genzet",
      value: 0,
    },
    {
      month: "03",
      unit: "kbn",
      type: "genzet",
      value: 0,
    },
    {
      month: "04",
      unit: "kbn",
      type: "genzet",
      value: 0,
    },
    {
      month: "05",
      unit: "kbn",
      type: "genzet",
      value: 0,
    },
    {
      month: "06",
      unit: "kbn",
      type: "genzet",
      value: 0,
    },
    {
      month: "07",
      unit: "kbn",
      type: "genzet",
      value: 0,
    },
    {
      month: "08",
      unit: "kbn",
      type: "genzet",
      value: 0,
    },
    {
      month: "09",
      unit: "kbn",
      type: "genzet",
      value: 0,
    },
    {
      month: "10",
      unit: "kbn",
      type: "genzet",
      value: 0,
    },
    {
      month: "11",
      unit: "kbn",
      type: "genzet",
      value: 0,
    },
    {
      month: "12",
      unit: "kbn",
      type: "genzet",
      value: 0,
    },
    {
      month: "01",
      unit: "cibitung",
      type: "genzet",
      value: 0,
    },
    {
      month: "02",
      unit: "cibitung",
      type: "genzet",
      value: 0,
    },
    {
      month: "03",
      unit: "cibitung",
      type: "genzet",
      value: 0,
    },
    {
      month: "04",
      unit: "cibitung",
      type: "genzet",
      value: 0,
    },
    {
      month: "05",
      unit: "cibitung",
      type: "genzet",
      value: 0,
    },
    {
      month: "06",
      unit: "cibitung",
      type: "genzet",
      value: 0,
    },
    {
      month: "07",
      unit: "cibitung",
      type: "genzet",
      value: 0,
    },
    {
      month: "08",
      unit: "cibitung",
      type: "genzet",
      value: 0,
    },
    {
      month: "09",
      unit: "cibitung",
      type: "genzet",
      value: 0,
    },
    {
      month: "10",
      unit: "cibitung",
      type: "genzet",
      value: 0,
    },
    {
      month: "11",
      unit: "cibitung",
      type: "genzet",
      value: 0,
    },
    {
      month: "12",
      unit: "cibitung",
      type: "genzet",
      value: 0,
    },
    {
      month: "01",
      unit: "cilincing",
      type: "solar",
      value: 0,
    },
    {
      month: "02",
      unit: "cilincing",
      type: "solar",
      value: 0,
    },
    {
      month: "03",
      unit: "cilincing",
      type: "solar",
      value: 0,
    },
    {
      month: "04",
      unit: "cilincing",
      type: "solar",
      value: 0,
    },
    {
      month: "05",
      unit: "cilincing",
      type: "solar",
      value: 0,
    },
    {
      month: "06",
      unit: "cilincing",
      type: "solar",
      value: 0,
    },
    {
      month: "07",
      unit: "cilincing",
      type: "solar",
      value: 0,
    },
    {
      month: "08",
      unit: "cilincing",
      type: "solar",
      value: 0,
    },
    {
      month: "09",
      unit: "cilincing",
      type: "solar",
      value: 0,
    },
    {
      month: "10",
      unit: "cilincing",
      type: "solar",
      value: 0,
    },
    {
      month: "11",
      unit: "cilincing",
      type: "solar",
      value: 0,
    },
    {
      month: "12",
      unit: "cilincing",
      type: "solar",
      value: 0,
    },
    {
      month: "01",
      unit: "kbn",
      type: "solar",
      value: 0,
    },
    {
      month: "02",
      unit: "kbn",
      type: "solar",
      value: 0,
    },
    {
      month: "03",
      unit: "kbn",
      type: "solar",
      value: 0,
    },
    {
      month: "04",
      unit: "kbn",
      type: "solar",
      value: 0,
    },
    {
      month: "05",
      unit: "kbn",
      type: "solar",
      value: 0,
    },
    {
      month: "06",
      unit: "kbn",
      type: "solar",
      value: 0,
    },
    {
      month: "07",
      unit: "kbn",
      type: "solar",
      value: 0,
    },
    {
      month: "08",
      unit: "kbn",
      type: "solar",
      value: 0,
    },
    {
      month: "09",
      unit: "kbn",
      type: "solar",
      value: 0,
    },
    {
      month: "10",
      unit: "kbn",
      type: "solar",
      value: 0,
    },
    {
      month: "11",
      unit: "kbn",
      type: "solar",
      value: 0,
    },
    {
      month: "12",
      unit: "kbn",
      type: "solar",
      value: 0,
    },
    {
      month: "01",
      unit: "cibitung",
      type: "solar",
      value: 0,
    },
    {
      month: "02",
      unit: "cibitung",
      type: "solar",
      value: 0,
    },
    {
      month: "03",
      unit: "cibitung",
      type: "solar",
      value: 0,
    },
    {
      month: "04",
      unit: "cibitung",
      type: "solar",
      value: 0,
    },
    {
      month: "05",
      unit: "cibitung",
      type: "solar",
      value: 0,
    },
    {
      month: "06",
      unit: "cibitung",
      type: "solar",
      value: 0,
    },
    {
      month: "07",
      unit: "cibitung",
      type: "solar",
      value: 0,
    },
    {
      month: "08",
      unit: "cibitung",
      type: "solar",
      value: 0,
    },
    {
      month: "09",
      unit: "cibitung",
      type: "solar",
      value: 0,
    },
    {
      month: "10",
      unit: "cibitung",
      type: "solar",
      value: 0,
    },
    {
      month: "11",
      unit: "cibitung",
      type: "solar",
      value: 0,
    },
    {
      month: "12",
      unit: "cibitung",
      type: "solar",
      value: 0,
    },
  ],
  message: "success",
};

export const chartJson = {
  data: [
    {
      asset_id: 'frequency',
      asset_name: 'Frequency',
      unit: 'Hz',
      data: [
        {
          time: 'January',
          value: 39890465,
          target: 0,
          current: false,
        },
        {
          time: 'February',
          value: 34728075,
          target: 0,
          current: false,
        },
        {
          time: 'March',
          value: 43422075,
          target: 0,
          current: false,
        },
        {
          time: 'April',
          value: 40434715,
          target: 0,
          current: false,
        },
        {
          time: 'May',
          value: 40901685,
          target: 0,
          current: false,
        },
        {
          time: 'June',
          value: 31345195,
          target: 0,
          current: false,
        },
        {
          time: 'July',
          value: 34054090,
          target: 0,
          current: false,
        },
        {
          time: 'August',
          value: 20752835,
          target: 0,
          current: false,
        },
        {
          time: 'September',
          value: 11066010,
          target: 0,
          current: false,
        },
        {
          time: 'October',
          value: 10387780,
          target: 0,
          current: true,
        },
        {
          time: 'November',
          value: 0,
          target: 20752835,
          current: false,
        },
        {
          time: 'December',
          value: 0,
          target: 10387780,
          current: false,
        },
      ],
    },
    {
      asset_id: 'tekanan_udara',
      asset_name: 'Tekanan Udara',
      unit: 'Pa/atm',
      data: [
        {
          time: 'January',
          value: 120170157,
          target: 0,
          current: false,
        },
        {
          time: 'February',
          value: 104738167.5,
          target: 0,
          current: false,
        },
        {
          time: 'March',
          value: 130752556.5,
          target: 0,
          current: false,
        },
        {
          time: 'April',
          value: 121804044.5,
          target: 0,
          current: false,
        },
        {
          time: 'May',
          value: 123057413.5,
          target: 0,
          current: false,
        },
        {
          time: 'June',
          value: 94337168.5,
          target: 0,
          current: false,
        },
        {
          time: 'July',
          value: 102432815,
          target: 0,
          current: false,
        },
        {
          time: 'August',
          value: 62382789,
          target: 0,
          current: false,
        },
        {
          time: 'September',
          value: 33471888,
          target: 0,
          current: false,
        },
        {
          time: 'October',
          value: 31415097.5,
          target: 0,
          current: true,
        },
        {
          time: 'November',
          value: 0,
          target: 30173844.6,
          current: false,
        },
        {
          time: 'December',
          value: 0,
          target: 30173844.6,
          current: false,
        },
      ],
    },
    // {
    //   asset_id: 'speed',
    //   asset_name: 'Speed',
    //   unit: 'rpm',
    //   data: [
    //     {
    //       time: 'January',
    //       value: 141426371,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'February',
    //       value: 123281785,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'March',
    //       value: 153865156,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'April',
    //       value: 143335946,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'May',
    //       value: 144797257,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'June',
    //       value: 111005520,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'July',
    //       value: 120530404,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'August',
    //       value: 73434485,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'September',
    //       value: 39419561,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'October',
    //       value: 36938882,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'November',
    //       value: 0,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'December',
    //       value: 0,
    //       target: 0,
    //       current: false,
    //     },
    //   ],
    // },
    // {
    //   asset_id: 'temperatur',
    //   asset_name: 'Temperatur',
    //   unit: '℃',
    //   data: [
    //     {
    //       time: 'January',
    //       value: 14116949.939669052,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'February',
    //       value: 12262359.348564042,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'March',
    //       value: 15383158.630520066,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'April',
    //       value: 14318916.979843039,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'May',
    //       value: 14521250.859769057,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'June',
    //       value: 11117555.277529025,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'July',
    //       value: 12092552.158133004,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'August',
    //       value: 7365040.375070014,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'September',
    //       value: 3896298.552793001,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'October',
    //       value: 3683417.3526039976,
    //       target: 0,
    //       current: true,
    //     },
    //     {
    //       time: 'November',
    //       value: 0,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'December',
    //       value: 0,
    //       target: 0,
    //       current: false,
    //     },
    //   ],
    // },
    // {
    //   asset_id: 'daya',
    //   asset_name: 'Daya',
    //   unit: 'kW',
    //   data: [
    //     {
    //       time: 'January',
    //       value: 3158718,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'February',
    //       value: 2750157,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'March',
    //       value: 3438585,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'April',
    //       value: 3202347,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'May',
    //       value: 3239486,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'June',
    //       value: 2482272,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'July',
    //       value: 2696957,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'August',
    //       value: 1643328,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'September',
    //       value: 876174,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'October',
    //       value: 819525,
    //       target: 0,
    //       current: true,
    //     },
    //     {
    //       time: 'November',
    //       value: 0,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'December',
    //       value: 0,
    //       target: 0,
    //       current: false,
    //     },
    //   ],
    // },
    // {
    //   asset_id: 'liquid_level',
    //   asset_name: 'Liquid Level',
    //   unit: 'cm',
    //   data: [
    //     {
    //       time: 'January',
    //       value: 7708263.779999997,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'February',
    //       value: 6718330.679999997,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'March',
    //       value: 8386363.129999996,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'April',
    //       value: 7812154.169999997,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'May',
    //       value: 7892691.389999997,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'June',
    //       value: 6050578.129999997,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'July',
    //       value: 6569554.859999998,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'August',
    //       value: 3998446.5899999985,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'September',
    //       value: 2146256.1999999997,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'October',
    //       value: 2001623.3999999994,
    //       target: 0,
    //       current: true,
    //     },
    //     {
    //       time: 'November',
    //       value: 0,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'December',
    //       value: 0,
    //       target: 0,
    //       current: false,
    //     },
    //   ],
    // },
    // {
    //   asset_id: 'percent',
    //   asset_name: 'Percent',
    //   unit: '%',
    //   data: [
    //     {
    //       time: 'January',
    //       value: 16472251.162660932,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'February',
    //       value: 14354116.967855003,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'March',
    //       value: 17921949.658720944,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'April',
    //       value: 16694379.761589,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'May',
    //       value: 16867684.260128975,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'June',
    //       value: 12930749.869822,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'July',
    //       value: 14041010.766749024,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'August',
    //       value: 8550458.079537984,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'September',
    //       value: 4597085.49043002,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'October',
    //       value: 4302644.890207019,
    //       target: 0,
    //       current: true,
    //     },
    //     {
    //       time: 'November',
    //       value: 0,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'December',
    //       value: 0,
    //       target: 0,
    //       current: false,
    //     },
    //   ],
    // },
  ],
  message: 'success',
  success: true,
  summary: [
    {
      asset_id: 'frequency',
      asset_name: 'Frequency',
      unit: 'Hz',
      data: [
        {
          time: 'average',
          value: 24080840,
          target: 0,
          current: false,
        },
        {
          time: 'count',
          value: 10,
          target: 0,
          current: false,
        },
        {
          time: 'total',
          value: 240808400,
          target: 0,
          current: false,
        },
      ],
    },
    {
      asset_id: 'tekanan_udara',
      asset_name: 'Tekanan Udara',
      unit: 'Pa/atm',
      data: [
        {
          time: 'average',
          value: 30173844.6,
          target: 0,
          current: false,
        },
        {
          time: 'count',
          value: 10,
          target: 0,
          current: false,
        },
        {
          time: 'total',
          value: 301738446,
          target: 0,
          current: false,
        },
      ],
    },
    // {
    //   asset_id: 'speed',
    //   asset_name: 'Speed',
    //   unit: 'rpm',
    //   data: [
    //     {
    //       time: 'average',
    //       value: 0,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'count',
    //       value: 0,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'total',
    //       value: 0,
    //       target: 0,
    //       current: false,
    //     },
    //   ],
    // },
    // {
    //   asset_id: 'temperatur',
    //   asset_name: 'Temperatur',
    //   unit: '℃',
    //   data: [
    //     {
    //       time: 'average',
    //       value: 3974520,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'count',
    //       value: 10,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'total',
    //       value: 39745200,
    //       target: 0,
    //       current: false,
    //     },
    //   ],
    // },
    // {
    //   asset_id: 'daya',
    //   asset_name: 'Daya',
    //   unit: 'kW',
    //   data: [
    //     {
    //       time: 'average',
    //       value: 2430754.9,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'count',
    //       value: 10,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'total',
    //       value: 24307549,
    //       target: 0,
    //       current: false,
    //     },
    //   ],
    // },
    // {
    //   asset_id: 'liquid_level',
    //   asset_name: 'Liquid Level',
    //   unit: 'cm',
    //   data: [
    //     {
    //       time: 'average',
    //       value: 5958720.9,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'count',
    //       value: 10,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'total',
    //       value: 59587209,
    //       target: 0,
    //       current: false,
    //     },
    //   ],
    // },
    // {
    //   asset_id: 'percent',
    //   asset_name: 'Percent',
    //   unit: '%',
    //   data: [
    //     {
    //       time: 'average',
    //       value: 5118394,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'count',
    //       value: 10,
    //       target: 0,
    //       current: false,
    //     },
    //     {
    //       time: 'total',
    //       value: 51183940,
    //       target: 0,
    //       current: false,
    //     },
    //   ],
    // },
  ],
};

